# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat4all_pb2 as chat4all__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat4all_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """===================================================
    1. Definição dos Serviços (Interface da API)
    ===================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetToken = channel.unary_unary(
                '/chat4all.ChatService/GetToken',
                request_serializer=chat4all__pb2.TokenRequest.SerializeToString,
                response_deserializer=chat4all__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.CreateConversation = channel.unary_unary(
                '/chat4all.ChatService/CreateConversation',
                request_serializer=chat4all__pb2.ConversationCreateRequest.SerializeToString,
                response_deserializer=chat4all__pb2.Conversation.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_stream(
                '/chat4all.ChatService/ListMessages',
                request_serializer=chat4all__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=chat4all__pb2.Message.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/chat4all.ChatService/SendMessage',
                request_serializer=chat4all__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=chat4all__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.ReceiveNotification = channel.unary_unary(
                '/chat4all.ChatService/ReceiveNotification',
                request_serializer=chat4all__pb2.NotificationRequest.SerializeToString,
                response_deserializer=chat4all__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.MapUser = channel.unary_unary(
                '/chat4all.ChatService/MapUser',
                request_serializer=chat4all__pb2.MapUserRequest.SerializeToString,
                response_deserializer=chat4all__pb2.MapUserResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """===================================================
    1. Definição dos Serviços (Interface da API)
    ===================================================

    """

    def GetToken(self, request, context):
        """6.1 Autenticação
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConversation(self, request, context):
        """6.2 Conversas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """6.2 Listar Mensagens (Server Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """6.3 Enviar Mensagem (Ingestão)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveNotification(self, request, context):
        """6.4 Receber Notificação de Status (Callback/Webhook)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapUser(self, request, context):
        """NOVO: RPC para Mapear Usuários (Se você for adicionar este serviço na API)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=chat4all__pb2.TokenRequest.FromString,
                    response_serializer=chat4all__pb2.TokenResponse.SerializeToString,
            ),
            'CreateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversation,
                    request_deserializer=chat4all__pb2.ConversationCreateRequest.FromString,
                    response_serializer=chat4all__pb2.Conversation.SerializeToString,
            ),
            'ListMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=chat4all__pb2.ListMessagesRequest.FromString,
                    response_serializer=chat4all__pb2.Message.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chat4all__pb2.SendMessageRequest.FromString,
                    response_serializer=chat4all__pb2.SendMessageResponse.SerializeToString,
            ),
            'ReceiveNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveNotification,
                    request_deserializer=chat4all__pb2.NotificationRequest.FromString,
                    response_serializer=chat4all__pb2.NotificationResponse.SerializeToString,
            ),
            'MapUser': grpc.unary_unary_rpc_method_handler(
                    servicer.MapUser,
                    request_deserializer=chat4all__pb2.MapUserRequest.FromString,
                    response_serializer=chat4all__pb2.MapUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat4all.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat4all.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """===================================================
    1. Definição dos Serviços (Interface da API)
    ===================================================

    """

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.ChatService/GetToken',
            chat4all__pb2.TokenRequest.SerializeToString,
            chat4all__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.ChatService/CreateConversation',
            chat4all__pb2.ConversationCreateRequest.SerializeToString,
            chat4all__pb2.Conversation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat4all.ChatService/ListMessages',
            chat4all__pb2.ListMessagesRequest.SerializeToString,
            chat4all__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.ChatService/SendMessage',
            chat4all__pb2.SendMessageRequest.SerializeToString,
            chat4all__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.ChatService/ReceiveNotification',
            chat4all__pb2.NotificationRequest.SerializeToString,
            chat4all__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MapUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.ChatService/MapUser',
            chat4all__pb2.MapUserRequest.SerializeToString,
            chat4all__pb2.MapUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileServiceStub(object):
    """--- SERVIÇO DE ARQUIVOS (Object Storage Gateway) ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUploadUrl = channel.unary_unary(
                '/chat4all.FileService/GetUploadUrl',
                request_serializer=chat4all__pb2.GetUploadUrlRequest.SerializeToString,
                response_deserializer=chat4all__pb2.GetUploadUrlResponse.FromString,
                _registered_method=True)
        self.CompleteUpload = channel.unary_unary(
                '/chat4all.FileService/CompleteUpload',
                request_serializer=chat4all__pb2.CompleteUploadRequest.SerializeToString,
                response_deserializer=chat4all__pb2.CompleteUploadResponse.FromString,
                _registered_method=True)
        self.GetDownloadUrl = channel.unary_unary(
                '/chat4all.FileService/GetDownloadUrl',
                request_serializer=chat4all__pb2.GetDownloadUrlRequest.SerializeToString,
                response_deserializer=chat4all__pb2.GetDownloadUrlResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """--- SERVIÇO DE ARQUIVOS (Object Storage Gateway) ---

    """

    def GetUploadUrl(self, request, context):
        """1. Inicia o upload e retorna URLs pré-assinadas para as partes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteUpload(self, request, context):
        """2. Finaliza o upload multipart no Object Storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadUrl(self, request, context):
        """3. Retorna uma URL temporária para download
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploadUrl,
                    request_deserializer=chat4all__pb2.GetUploadUrlRequest.FromString,
                    response_serializer=chat4all__pb2.GetUploadUrlResponse.SerializeToString,
            ),
            'CompleteUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteUpload,
                    request_deserializer=chat4all__pb2.CompleteUploadRequest.FromString,
                    response_serializer=chat4all__pb2.CompleteUploadResponse.SerializeToString,
            ),
            'GetDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadUrl,
                    request_deserializer=chat4all__pb2.GetDownloadUrlRequest.FromString,
                    response_serializer=chat4all__pb2.GetDownloadUrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat4all.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat4all.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """--- SERVIÇO DE ARQUIVOS (Object Storage Gateway) ---

    """

    @staticmethod
    def GetUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.FileService/GetUploadUrl',
            chat4all__pb2.GetUploadUrlRequest.SerializeToString,
            chat4all__pb2.GetUploadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.FileService/CompleteUpload',
            chat4all__pb2.CompleteUploadRequest.SerializeToString,
            chat4all__pb2.CompleteUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat4all.FileService/GetDownloadUrl',
            chat4all__pb2.GetDownloadUrlRequest.SerializeToString,
            chat4all__pb2.GetDownloadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
